INFRA:
  - changed-files:
    - any-glob-to-any-file: [
      '.github/**/*',
      '.gitignore',
      '.gitattributes',
      '.gitmodules'
    ]

DOCS:
  - changed-files:
    - any-glob-to-any-file: [
      '**/README.md',
      '**/CONTRIBUTING.md'
    ]

CORE:
  - changed-files:
    - any-glob-to-any-file: [
      'cloaken/**/*',
      'phishdecloaker/**/*',
      'datasets/**/*'
    ]
