# pyproject.toml

[tool.isort]
profile = "black"  
# 如果您同时使用, Black可以选择与 Black 兼容的配置
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
skip_glob = [
    "**/migrations/**",
    "**/__init__.py",
]