name: Complete Code Anayl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.24
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_HOST: tcp://localhost:2375

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # You can adjust the Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint pytest coverage pytest-cov pytest-benchmark
      
      - name: Run Flake8 for Code Style Checks
        run: |
          flake8 phishdecloaker/ captcha_solvers/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 phishdecloaker/ captcha_solvers/ --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Run Pylint for Code Quality
        run: |
          pylint phishdecloaker/ captcha_solvers/

      - name: Run Unit Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --cov=phishdecloaker --cov=captcha_solvers --cov-report=xml --cov-report=term-missing

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true

  docker-build-test:
    name: Build and Test Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Images
        run: |
          docker build -t phishdecloaker:latest -f Dockerfile .

      - name: Run Dockerized Tests
        run: |
          docker run --rm phishdecloaker:latest pytest
