name: Code style checks

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/code_style.yml'
      - 'phishdecloaker/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/code_style.yml'
      - 'phishdecloaker/**'

jobs:
  lint-format-test:
    defaults:
      run:
        shell: bash -l {0}

    name: CI - Lint, Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"

      - name: Cache Conda packages
        uses: actions/cache@v3
        with:
          path: ~/miniconda3/pkgs
          key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Find all environment.yml files
        id: find_env
        run: |
          echo "env_files<<EOF" >> $GITHUB_ENV
          find . -type f -name "environment.yml" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Process each environment.yml
        run: |
          # Initialize Conda in the current shell
          source ~/miniconda3/etc/profile.d/conda.sh

          for env_file in $(find . -type f -name "environment.yml"); do
            echo "Processing $env_file"

            # Get project name (e.g., captcha_detector)
            project_dir=$(dirname "$env_file")
            project_name=$(basename "$project_dir")

            # Create a unique environment name
            env_name="${project_name}_env"

            # Create or update the Conda environment
            conda env create -f "$env_file" -n "$env_name" || conda env update -f "$env_file" -n "$env_name"

            # Activate the environment
            conda init
            conda activate "$env_name"

            # Install code quality check tools (if not included in environment.yml)
            pip install black flake8 mypy bandit vulture pytest

            # Run code quality checks
            black --check "$project_dir"
            flake8 "$project_dir" --ignore=E203,W503
            mypy "$project_dir" --explicit-package-bases
            bandit -r "$project_dir"
            vulture "$project_dir"

            # Run tests (if applicable)
            if [ -d "${project_dir}/tests" ]; then
              mkdir -p reports
              pytest "$project_dir/tests" --junitxml=reports/${project_name}_test-results.xml
            fi

            # Deactivate the environment
            conda deactivate
          done
