name: Python Code Quality and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: pip install --upgrade pip
      - run: pip install flake8 black pytest
      - run: black --check .
      - run: flake8 .
      - run: pytest
